### ISSUE TITLE
Why save numchild in the database?

### ISSUE THREAD

**Issue by alexgleason** [django-treebeard/django-treebeard#107]
Forgive me if this is daft, I'm just curious. My instinct is that numchild should be calculated at runtime and cached if necessary rather than stored in the DB. If a child were deleted without the parent being updated, numchild would be out of sync.

**Comment by jrief** [comment]
Using the MP tree, computing the number of children of a node is not super simple. In SQL you would have to do something such as:
```
SELECT COUNT(*) FROM mp_node WHERE path LIKE 'xxxx%' AND LENGTH(path) = y + 4;
```
whereas `xxxx` is the content of the parent node's path field and `y` is the length of that field.

Gutavo Picón probably wanted to avoid this additional query.

**Comment by tabo** [comment]
Correct. it is an optimization for a very expensive and common operation. Particularly in treebeard's internals, the `numchild` attribute is used by "is_leaf()" (true if a node has no children), and this method is used a lot to avoid even more unnecessary queries.

The problem with `numchild` as you can imagine is what happens when it goes out of sync, something that should never happens if the user is following the docs and is diligent with database transactions.
