### ISSUE TITLE
djaango 3.0 supported?

### ISSUE THREAD

**Issue by auvipy** [django-treebeard/django-treebeard#148]

**Comment by thelittlebug** [comment]
i have no idea if it "supports" 3.0, but im using it with django 3.0.6 and wagtail in production without any issue

**Comment by jrief** [comment]
Django-CMS also uses treebeard on Django-3.0 without any issues.

**Comment by coredumperror** [comment]
The only thing I'm personally see wrong with Treebeard and Django 3.0 is that 3.0 officially deprecated `ugettext_lazy`, and if you run `python -Wall`, you'll get a ton of `RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().` from Treebeard's code.

However, since `ugettext_lazy` has been an alias of `gettext_lazy` [since Django 2.0](https://docs.djangoproject.com/en/3.0/_modules/django/utils/translation/#gettext), the fix is a simple search-and-replace.
