### ISSUE TITLE
add_root raise  Cannot use None as a query value

### ISSUE THREAD

**Issue by kingctan** [django-treebeard/django-treebeard#156]

**Comment by tabo** [comment]
There is no description or details. `add_root()` is well tested. We need more information to help you.

**Comment by shaggyfrog** [comment]
I just ran into the same issue, where `node_order_by` for my model class uses a `DateTimeField` with `auto_now_add=True`; since the value for that field is not set until `save()` is called on the instance, the call to `add_root()` fails inside `django.db.models.sql.query.Query.build_lookup()` since the `lookup.rhs` value is `None`.

**Comment by shacker** [comment]
I encountered this in a similar situation, where I had this on the model

```
order = models.IntegerField(null=True)

node_order_by = ['order']
```
and was creating instances without specifying an order (thinking that null=True made it optional).

I could create the first instance, but it fails with this error when you go to create the second, since it is trying to order on null fields, or something along those lines.
