### ISSUE TITLE
Fix role hierarchy using django migration

### ISSUE THREAD

**Issue by maruthi8** [django-treebeard/django-treebeard#181]
I want to write django migration while to generate required tree structure.

But when I am doing it it gives me error `Model_name` does not have `move`.
```
for child in parent_child_mapping[role]:
      child = Role.objects.get(name=child)
      # move it as child of parent role
      child.move(parent_role, "last-child")
```

Is their anyother better way to do this?

**Comment by solarissmoke** [comment]
Models in migrations not having custom methods available is [documented behaviour](https://docs.djangoproject.com/en/3.1/topics/migrations/#historical-models). You can find some suggestions for how to work around this [here](https://stackoverflow.com/questions/28777338/django-migrations-runpython-not-able-to-call-model-methods) - alternatively consider doing this in a management command instead of a migration.
