### ISSUE TITLE
The delete method should bring up to date with current Django standards

### ISSUE THREAD

**Issue by tabo** [django-treebeard/django-treebeard#197]
As reported in #141, Django 2+ returns a value on [delete()](https://docs.djangoproject.com/en/3.1/ref/models/querysets/#delete). 

We need to update this behavior, which would be a breaking change since the[ API doesn't mention a return value at the moment](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.delete).

There is an  first attempt at an implementation in #141 but it is only for MP trees and it has no tests.

Necessary tasks:

- [ ] Edit all the tests that call delete to assert they return an expected value
- [ ] Update MP delete
- [ ] Update NS delete
- [ ] Update AL delete
- [ ] Update delete documentation
- [ ] Prepare a new major release

**Comment by johanneswilm** [comment]
@tabo Ok, but since it doesn't return any value currently, could it really potentially break existing apps? Why would one store the return value of `delete()` if there is none?

**Comment by tabo** [comment]
@johanneswilm Good point. I don't think it would break any app, but it does change the API.

**Comment by BigE** [comment]
The original problem I encountered is that there is an expected return value from the QuerySet API for the `delete()` method that includes the number of rows deleted along with each deleted record. I came across this issue in a Wagtail project and I did find another solution, rather than relying on this change... but the QuerySet API is essentially changed from the original API behavior.

I don't have a personal preference and I'm not sure what the additional effort would be to get #141 up to a more acceptable place, but I think it's potentially worth it just to keep the QuerySet API consistent. I'd be happy to put more effort into it as well, if it would help.

**Comment by tabo** [comment]
@BigE I think the main problem with the original PR was that it only addressed MP trees, but we would have to modify AL and NS too. Additionally, we would need new tests, documentation updates, and since this would be a change to the API, a new major release would have to be made.
