### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by benharvie** [django-treebeard/django-treebeard#258]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@goodguyandy) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by timoludwig** [comment]
@jrief @mvantellingen @tabo @yakky what is the maintenance status of this project?

If you no longer have the time or will to maintain this library, please put a disclaimer in the readme to point out that this library is no longer supported and people should move to alternatives or fork this library to provide security updates at least for all [7,7k projects that depend on this library](https://github.com/django-treebeard/django-treebeard/network/dependents), including e.g. the widely used [django-cms](https://github.com/django-cms/django-cms).

I understand that open source development is often not very rewarding, but in my opinion you have the responsibility to the community to tell when you're no longer willing or able to maintain a project instead of just ignoring all issues and PRs.

That said, thanks a lot for your efforts in the past, let me know if you would accept any help in the form of donations or working hours in order to keep this library updated.

**Comment by solarissmoke** [comment]
Hi there. I've just added [instructions](https://github.com/django-treebeard/django-treebeard/blob/master/SECURITY.md) for reporting a vulnerability - would be grateful if you can do that now. Thank you.
