### ISSUE TITLE
How to defragment 

### ISSUE THREAD

**Issue by HugoSPT** [django-treebeard/django-treebeard#99]
Hi,

There is any way to run django-treebeard over all pages (and children) and defragment the path to fill the gaps in the path between published/active pages and deleted ones? Basically to build the tree again going through the current existing pages with refreshed (and no gaps) paths.

I am asking it because when I run `fix_tree(destructive=True)` I get a key error when dealing with orphan nodes. With `destructive` set to `False` nothing is fixed in the tree.

Thank you.

**Comment by 4levels** [comment]
Hi,

I have a similar issue when deleting nodes having foreignKey relations in MP trees: somehow the fix_tree(True) class method fails every time.  If called without desctructive (the default) the tree paths are not fixed (as documented)

After deleting a node using the node.delete() method, the tree paths show gaps.  I've been trying to search for a method to only fix the tree paths (since the fix_tree(True) call is failing as well), but I'm still failing to do this.

I can imagine I'll have to write my own routine to fix the paths starting from the node I'm about to delete.  Since MP trees are database-friendly (compared to eg. nested sets) this might turn out to be not too difficult after all.

Any pointers on how to fix only the paths in a MP tree are greatly appreciated though...

Kind regards and keep up this amazing library!

Erik

**Comment by HugoSPT** [comment]
Ended up writing my own function to re-write the tree's node paths.

**Comment by 4levels** [comment]
Hi @HugoSPT,

I'm about to start this as well, can you share some of your code?

Thanks in advance!

**Comment by HugoSPT** [comment]
https://git.gw20e.com/snippets/87

**Doesn't take care of orphans.**

**Comment by 4levels** [comment]
Hi @HugoSPT,

that's fast - and a lot to take in for my beginner python brain ;-)
I'm seeing calls to `_inc_path` and `_get_path` functions, is that where the magic happens?

Allthough your solution looks very elegant, I'm not really understanding much of it just yet.  I'm currently fetching all siblings and fixing the paths using NumConv's functions to build an update data set, that I can run at once (instead of saving each node individually).

Thanks for the quick responses, I'll post my end result here as well (looking for a short solution obviously)

Kind regards,

Erik

**Comment by HugoSPT** [comment]
Those private functions are coming from `Page`. As you can see, `InMemoryPage` inherits from `Page`

**Comment by 4levels** [comment]
I'm currently selecting all sibling nodes as follows, where node_path and node_depth are from the node to be deleted.  So far this works great, all I need to add now is some simple path additions using the NumConv's functions..

```python
            nodes = Tree.objects.filter(
                path__startswith=node_path[:-4],
                path__gt=node_path,
                depth=node_depth)
```

Gotta go now (EST timezone), thanks again!

**Comment by 4levels** [comment]
Hi @HugoSPT,

I've spent all day trying to get this to work, but I'm failing miserably.
Besides that, I still don't understand how your snippet is actually changing anything in the node's path value (I'm not using djangocms, just django and django-treebeard).

I filed a new issue for this as this issue seems now permanently going wrong, even in the Django admin - see #123 

This is the furthest I got, but doesn't work reliably as there seems to be caching issues (or what more beyond my comprehension) that keep this from succeeding.  According to the docs, we shouldn't manipulate the `path`, `depth` and `numchild` attributes anyway...
It works most of the time, but when I move nodes having children to different nodes, still not all node paths are correctly adjusted.

Helper method in my MP_NodeManager extended class:

```python

# custom tree manager
class TreeManager(MP_NodeManager):

    def fix_tree_paths(self, path, depth, nodes=None):
        """
        Due to an issue with Treebeard, gaps are not fixed automatically after
        deleting a node - see ao
        https://github.com/django-treebeard/django-treebeard/issues/99
        Manually fix paths by getting all sibling nodes after the current and
        using NumConv functions to adjust the paths
        """

        # get all other sibling nodes from and including the given path
        if nodes is None:
            nodes = Tree.objects.filter(
                path__startswith=path[:-1*Tree.steplen],
                path__gte=path,
                depth=depth)

        path_int = str2int(path[-1*Tree.steplen:].lstrip('0'),
                           len(Tree.alphabet))

        result = []

        # with transaction.atomic():
        for n in nodes:

            """
            Because MPNode paths are strings of Tree.steplen's length, use
            string trimming to update only the corresponding part
            use current node's depth to determine which part to replace
            """
            new_path = path[:-1*Tree.steplen*(n.depth-depth+1)] + (
                '{:0>'+str(Tree.steplen)+'}').format(
                    int2str(path_int, len(Tree.alphabet))
                )
            n.path = new_path
            n.save()

            result.append([
                n.pk,
                "<strong>%s</strong> %s" % (
                    n.path, n.title
                )])

            path_int = path_int + 1

            # recursing into children if needed
            if n.get_children_count():
                result = result + self.fix_tree_paths(
                    n.get_first_child().path, n.depth+1, 
                    nodes=n.get_children())

        return result
```

I even tried brute forcing move operations on all sibling nodes for the current node but to no avail.
Only if I move a node with a wrong path the a different position, followed by a second move back to it's original position, I see the gaps disappearing.  This approach however is insane imho and takes considerably long.  I even tried Tree.load_bulk(Tree.dump_bulk()) but since my Tree model has relations that can be blank (`null=True, blank=True`) this fails consistently as soon as one record has an empty relation (apparently a known caveat, sigh)

Can you explain a little about your snippet how it actually works?  Does it fix the `path` values in the database to be a consistent sequence?

Kind regards,

Erik

**Comment by 4levels** [comment]
Hi @HugoSPT,

I think I managed to write a successfull and efficient path defragmentation routine (as in my previous reply).
This method can be called after any move / delete operations and only needs a reference to the modified node's parent to work.  I'm deliberately not relying on the MP_node's helper functions (like `get_children()`) to prevent caching issues.  I also managed to remove all references to specific model names (since this is called from a manager) so this can work in a generic way.

```python
from django.db import models, transaction
from treebeard.mp_tree import MP_NodeManager
from numconv import int2str, str2int

# custom tree manager
class TreeManager(MP_NodeManager):

    """
    Due to an issue with Treebeard, gaps are not fixed automatically after
    deleting or moving a node - see ao.
    https://github.com/django-treebeard/django-treebeard/issues/123
    Manually fix paths by getting all descendant nodes by using NumConv
    functions to adjust the paths.  Works recursively
    Expects the parent node of the modified / deleted node
    """
    def fix_tree_paths(self, node):

        result = []

        if node and isinstance(node, self.model):

            # get direct descendants only
            nodes = super().get_queryset().filter(
                path__startswith=node.path,
                depth=(1 + node.depth)
            )

        if nodes and len(nodes) > 0:

            index = 1

            with transaction.atomic():
                for node in nodes:
                    """
                    Because MP_Node paths are strings of self.model.steplen's length, use
                    string slicing to update only the corresponding part
                    """

                    new_path = node.path[:-1*self.model.steplen] + (
                        '{:0>'+str(self.model.steplen)+'}').format(
                            int2str(index, len(self.model.alphabet))
                        )

                    node.path = new_path
                    node.save()

                    result.append(node.pk)

                    index = index + 1

                    # recursion if needed
                    if node.numchild > 0:
                        result = result + self.fix_tree_paths(node)

        return result

```

Hope this helps someone facing the same issues..

**Comment by tabo** [comment]
There is a new (safe!) implementation of `fix_tree()` in #165 that solves this issue
